"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AppLogo } from "@/components/AppLogo";
import { getSupabase } from "@/lib/supabase-browser";

const slugify=(value:string)=>value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
export default function OnboardingPage(){const router=useRouter();const [name,setName]=useState("");const [slug,setSlug]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(false);useEffect(()=>{getSupabase().auth.getUser().then(({data})=>{if(!data.user)router.replace("/login")})},[router]);async function submit(e:FormEvent){e.preventDefault();setLoading(true);setError("");const {error:rpcError}=await getSupabase().rpc("register_organization",{org_name:name,org_slug:slug});if(rpcError){setError(rpcError.message);setLoading(false);return}router.replace("/app")}return <main className="onboarding-page"><header><AppLogo dark/><span>Step 1 of 2</span></header><section className="onboarding-grid"><div><span className="step-label">ORGANIZATION SETUP</span><h1>Let&apos;s build your election workspace.</h1><p>Your free workspace includes 50 eligible voters, one election and two positions. You can upgrade whenever you&apos;re ready.</p><ul><li>Tenant-isolated voter data</li><li>Organization-controlled eligibility</li><li>Secure vote receipts and audit logs</li></ul></div><form className="setup-card" onSubmit={submit}>{error&&<div className="form-error">{error}</div>}<label>Organization name<input value={name} onChange={e=>{setName(e.target.value);setSlug(slugify(e.target.value))}} placeholder="Example Student Association" required/></label><label>Workspace URL<div className="slug-input"><span>votiqra.com/</span><input value={slug} onChange={e=>setSlug(slugify(e.target.value))} placeholder="your-organization" required/></div></label><div className="free-plan-summary"><span>FREE PLAN</span><strong>₦0</strong><small>50 voters • 1 election • 2 positions</small></div><button className="button wide" disabled={loading}>{loading?"Creating workspace…":"Create workspace"}</button></form></section></main>}
